[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "slim disorder corn guide change plunge remember arch clever explain bargain width they noise joy same employ silly small own brick skill satisfy bind"
